#! /bin/sh
### BEGIN INIT INFO
# Provides:          kamailio
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Sascha Daniels <sascha.daniels@amooma.de>
#

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/opt/kamailio-3.1/sbin
DESC="Kamailio SIP Proxy"
NAME=kamailio
DAEMON=/opt/kamailio-3.1/sbin/kamctl
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

case $1 in
	start|stop|restart)
		echo -n "$1 $NAME\n"
		$DAEMON $1
	;;

	*)
		echo -e "Usage start|stop|restart"
	;;
esac



