#! /bin/sh

# `rake notes` doesn't find everything and is too slow.

find . -type f \
  | grep -vEe '/(\.git/|.idea/|doc/app/|script/notes|log/|debian/visual-inspection/|public/javascripts/controls\.js)' \
  | xargs grep --color -IEe '(TODO|FIXME|OPTIMIZE)'


